/*
 * This file is generated by jOOQ.
*/
package club.ndt.oauth.boot.entity;


import club.ndt.oauth.boot.entity.tables.OauthClientDetails;
import club.ndt.oauth.boot.entity.tables.TPersonalDetail;
import club.ndt.oauth.boot.entity.tables.TUser;
import club.ndt.oauth.boot.entity.tables.records.OauthClientDetailsRecord;
import club.ndt.oauth.boot.entity.tables.records.TPersonalDetailRecord;
import club.ndt.oauth.boot.entity.tables.records.TUserRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>ndt</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<OauthClientDetailsRecord> OAUTH_CLIENT_DETAILS_PKEY = UniqueKeys0.OAUTH_CLIENT_DETAILS_PKEY;
    public static final UniqueKey<TPersonalDetailRecord> T_PERSONAL_DETAIL_PKEY = UniqueKeys0.T_PERSONAL_DETAIL_PKEY;
    public static final UniqueKey<TUserRecord> T_USER_PKEY = UniqueKeys0.T_USER_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<OauthClientDetailsRecord> OAUTH_CLIENT_DETAILS_PKEY = Internal.createUniqueKey(OauthClientDetails.OAUTH_CLIENT_DETAILS, "oauth_client_details_pkey", OauthClientDetails.OAUTH_CLIENT_DETAILS.CLIENT_ID);
        public static final UniqueKey<TPersonalDetailRecord> T_PERSONAL_DETAIL_PKEY = Internal.createUniqueKey(TPersonalDetail.T_PERSONAL_DETAIL, "t_personal_detail_pkey", TPersonalDetail.T_PERSONAL_DETAIL.ID);
        public static final UniqueKey<TUserRecord> T_USER_PKEY = Internal.createUniqueKey(TUser.T_USER, "t_user_pkey", TUser.T_USER.ID);
    }
}
