/*
 * This file is generated by jOOQ.
*/
package club.ndt.oauth.boot.entity;


import club.ndt.oauth.boot.entity.tables.ActEvtLog;
import club.ndt.oauth.boot.entity.tables.ActGeBytearray;
import club.ndt.oauth.boot.entity.tables.ActGeProperty;
import club.ndt.oauth.boot.entity.tables.ActHiActinst;
import club.ndt.oauth.boot.entity.tables.ActHiAttachment;
import club.ndt.oauth.boot.entity.tables.ActHiComment;
import club.ndt.oauth.boot.entity.tables.ActHiDetail;
import club.ndt.oauth.boot.entity.tables.ActHiIdentitylink;
import club.ndt.oauth.boot.entity.tables.ActHiProcinst;
import club.ndt.oauth.boot.entity.tables.ActHiTaskinst;
import club.ndt.oauth.boot.entity.tables.ActHiVarinst;
import club.ndt.oauth.boot.entity.tables.ActIdGroup;
import club.ndt.oauth.boot.entity.tables.ActIdInfo;
import club.ndt.oauth.boot.entity.tables.ActIdMembership;
import club.ndt.oauth.boot.entity.tables.ActIdUser;
import club.ndt.oauth.boot.entity.tables.ActProcdefInfo;
import club.ndt.oauth.boot.entity.tables.ActReDeployment;
import club.ndt.oauth.boot.entity.tables.ActReModel;
import club.ndt.oauth.boot.entity.tables.ActReProcdef;
import club.ndt.oauth.boot.entity.tables.ActRuEventSubscr;
import club.ndt.oauth.boot.entity.tables.ActRuExecution;
import club.ndt.oauth.boot.entity.tables.ActRuIdentitylink;
import club.ndt.oauth.boot.entity.tables.ActRuJob;
import club.ndt.oauth.boot.entity.tables.ActRuTask;
import club.ndt.oauth.boot.entity.tables.ActRuVariable;
import club.ndt.oauth.boot.entity.tables.CAdminDivision;
import club.ndt.oauth.boot.entity.tables.CDictMapping;
import club.ndt.oauth.boot.entity.tables.CDictType;
import club.ndt.oauth.boot.entity.tables.CSensitiveWords;
import club.ndt.oauth.boot.entity.tables.MtMessageAccepter;
import club.ndt.oauth.boot.entity.tables.MtRoleMenu;
import club.ndt.oauth.boot.entity.tables.MtUserRole;
import club.ndt.oauth.boot.entity.tables.OauthAccessToken;
import club.ndt.oauth.boot.entity.tables.OauthClientDetails;
import club.ndt.oauth.boot.entity.tables.OauthCode;
import club.ndt.oauth.boot.entity.tables.OauthRefreshToken;
import club.ndt.oauth.boot.entity.tables.TAdvert;
import club.ndt.oauth.boot.entity.tables.TAdvertBak;
import club.ndt.oauth.boot.entity.tables.TAppVersion;
import club.ndt.oauth.boot.entity.tables.TBanner;
import club.ndt.oauth.boot.entity.tables.TBannerBak;
import club.ndt.oauth.boot.entity.tables.TBannerModel;
import club.ndt.oauth.boot.entity.tables.TBusinessResource;
import club.ndt.oauth.boot.entity.tables.TButtonForm;
import club.ndt.oauth.boot.entity.tables.TCollection;
import club.ndt.oauth.boot.entity.tables.TCompanyDetail;
import club.ndt.oauth.boot.entity.tables.TCompanyDetailPrecheck;
import club.ndt.oauth.boot.entity.tables.TCompanyFinance;
import club.ndt.oauth.boot.entity.tables.TCompanyHonor;
import club.ndt.oauth.boot.entity.tables.TCompanyInsurance;
import club.ndt.oauth.boot.entity.tables.TCompanyInvestment;
import club.ndt.oauth.boot.entity.tables.TCompanyManagement;
import club.ndt.oauth.boot.entity.tables.TCompanyPayment;
import club.ndt.oauth.boot.entity.tables.TCompanyUnbindPreCheck;
import club.ndt.oauth.boot.entity.tables.TContentCheck;
import club.ndt.oauth.boot.entity.tables.TCooperation;
import club.ndt.oauth.boot.entity.tables.TCreditDivision;
import club.ndt.oauth.boot.entity.tables.TCreditRating;
import club.ndt.oauth.boot.entity.tables.TCreditTask;
import club.ndt.oauth.boot.entity.tables.TDiscountBaseInfo;
import club.ndt.oauth.boot.entity.tables.TDiscountCollection;
import club.ndt.oauth.boot.entity.tables.TDiscountScaleInfo;
import club.ndt.oauth.boot.entity.tables.TDiscountSync;
import club.ndt.oauth.boot.entity.tables.TFarm;
import club.ndt.oauth.boot.entity.tables.TFile;
import club.ndt.oauth.boot.entity.tables.TFinancialApply;
import club.ndt.oauth.boot.entity.tables.TFinancialSync;
import club.ndt.oauth.boot.entity.tables.TInfo;
import club.ndt.oauth.boot.entity.tables.TInfoWeb;
import club.ndt.oauth.boot.entity.tables.TInsureLoanOrder;
import club.ndt.oauth.boot.entity.tables.TInsureLoanProduct;
import club.ndt.oauth.boot.entity.tables.TInsureLoanTrace;
import club.ndt.oauth.boot.entity.tables.TInsureOrder;
import club.ndt.oauth.boot.entity.tables.TInsureProduct;
import club.ndt.oauth.boot.entity.tables.TIntegralRule;
import club.ndt.oauth.boot.entity.tables.TLargeBreeder;
import club.ndt.oauth.boot.entity.tables.TLeadingEnterprise;
import club.ndt.oauth.boot.entity.tables.TLoanApply;
import club.ndt.oauth.boot.entity.tables.TLoanApplyPond;
import club.ndt.oauth.boot.entity.tables.TLoanDone;
import club.ndt.oauth.boot.entity.tables.TLoanGuarantee;
import club.ndt.oauth.boot.entity.tables.TLoanHaorenApply;
import club.ndt.oauth.boot.entity.tables.TLoanInvitation;
import club.ndt.oauth.boot.entity.tables.TLoanOverdue;
import club.ndt.oauth.boot.entity.tables.TLoanPayoff;
import club.ndt.oauth.boot.entity.tables.TLoanProduct;
import club.ndt.oauth.boot.entity.tables.TLoanProductAnnex;
import club.ndt.oauth.boot.entity.tables.TLoanProductCostInfo;
import club.ndt.oauth.boot.entity.tables.TLoanProductDataInfo;
import club.ndt.oauth.boot.entity.tables.TLoanRaidBs;
import club.ndt.oauth.boot.entity.tables.TLoanRecord;
import club.ndt.oauth.boot.entity.tables.TLoanTerm;
import club.ndt.oauth.boot.entity.tables.TLoanflowSync;
import club.ndt.oauth.boot.entity.tables.TLoanproductSyncconfig;
import club.ndt.oauth.boot.entity.tables.TLoginLog;
import club.ndt.oauth.boot.entity.tables.TLotteryRecord;
import club.ndt.oauth.boot.entity.tables.TMajorProject;
import club.ndt.oauth.boot.entity.tables.TMenu;
import club.ndt.oauth.boot.entity.tables.TMessage;
import club.ndt.oauth.boot.entity.tables.TNationalDebtDots;
import club.ndt.oauth.boot.entity.tables.TNationalDebtDotsCopy1;
import club.ndt.oauth.boot.entity.tables.TNationalDebtOrders;
import club.ndt.oauth.boot.entity.tables.TNationalDebtProduct;
import club.ndt.oauth.boot.entity.tables.TNationalDebtTerm;
import club.ndt.oauth.boot.entity.tables.TOperLog;
import club.ndt.oauth.boot.entity.tables.TOrderDetail;
import club.ndt.oauth.boot.entity.tables.TOrderInfo;
import club.ndt.oauth.boot.entity.tables.TOrg;
import club.ndt.oauth.boot.entity.tables.TPersonCompanyRel;
import club.ndt.oauth.boot.entity.tables.TPersonCompanyUnbindRel;
import club.ndt.oauth.boot.entity.tables.TPersonalDetail;
import club.ndt.oauth.boot.entity.tables.TPolicy;
import club.ndt.oauth.boot.entity.tables.TPolicyService;
import club.ndt.oauth.boot.entity.tables.TPolicyServiceApply;
import club.ndt.oauth.boot.entity.tables.TPolicyServiceMaterial;
import club.ndt.oauth.boot.entity.tables.TPolicyServiceRadix;
import club.ndt.oauth.boot.entity.tables.TPolicyServiceSync;
import club.ndt.oauth.boot.entity.tables.TProfessionAgent;
import club.ndt.oauth.boot.entity.tables.TPropertyRightsTrading;
import club.ndt.oauth.boot.entity.tables.TQrCodeInfo;
import club.ndt.oauth.boot.entity.tables.TQuestionnaire;
import club.ndt.oauth.boot.entity.tables.TRecommendation;
import club.ndt.oauth.boot.entity.tables.TRisksShare;
import club.ndt.oauth.boot.entity.tables.TRisksShareTrace;
import club.ndt.oauth.boot.entity.tables.TRiskshareApply;
import club.ndt.oauth.boot.entity.tables.TRiskshareApplyProcess;
import club.ndt.oauth.boot.entity.tables.TRiskshareDone;
import club.ndt.oauth.boot.entity.tables.TRole;
import club.ndt.oauth.boot.entity.tables.TScoreTrace;
import club.ndt.oauth.boot.entity.tables.TShopWare;
import club.ndt.oauth.boot.entity.tables.TShopWareInfo;
import club.ndt.oauth.boot.entity.tables.TSignRecord;
import club.ndt.oauth.boot.entity.tables.TSiteMessage;
import club.ndt.oauth.boot.entity.tables.TSmallLoanOrder;
import club.ndt.oauth.boot.entity.tables.TSmallLoanProduct;
import club.ndt.oauth.boot.entity.tables.TSmallLoanTrace;
import club.ndt.oauth.boot.entity.tables.TSms;
import club.ndt.oauth.boot.entity.tables.TStandardRate;
import club.ndt.oauth.boot.entity.tables.TStaticSource;
import club.ndt.oauth.boot.entity.tables.TStaticSourceBak;
import club.ndt.oauth.boot.entity.tables.TStepBase;
import club.ndt.oauth.boot.entity.tables.TStepButton;
import club.ndt.oauth.boot.entity.tables.TTermBase;
import club.ndt.oauth.boot.entity.tables.TThirdUser;
import club.ndt.oauth.boot.entity.tables.TUser;
import club.ndt.oauth.boot.entity.tables.TUserCredit;
import club.ndt.oauth.boot.entity.tables.TUserCredittaskLog;
import club.ndt.oauth.boot.entity.tables.TUserInfoDetail;
import club.ndt.oauth.boot.entity.tables.TUserPropertyright;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyBaseinfo;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyBusiness;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyCredit;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyDetail;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyEmployment;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyEvaluation;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyFinance;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyHonor;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyInsurance;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyInvestment;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyKnowledge;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyLoan;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyManagement;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyPatent;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyPayment;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyPurchase;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyReward;
import club.ndt.oauth.boot.entity.tables.TVillageCompanySales;
import club.ndt.oauth.boot.entity.tables.TVillageCompanySubsidy;
import club.ndt.oauth.boot.entity.tables.TVillageCompanyWarrant;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalAwardsPunishments;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalBaseinfo;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalCarinfo;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalCreditRating;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalCreditTitle;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalDetail;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalEquipment;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalHouse;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalInsured;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalOtherinfo;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalPatent;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalPayment;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalProductioninfo;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalPurchasing;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalRecruitment;
import club.ndt.oauth.boot.entity.tables.TVillagePersonalWarrantinfo;
import club.ndt.oauth.boot.entity.tables.VStatisticsUser;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Sequence;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.8"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Ndt extends SchemaImpl {

    private static final long serialVersionUID = -1041210487;

    /**
     * The reference instance of <code>ndt</code>
     */
    public static final Ndt NDT = new Ndt();

    /**
     * The table <code>ndt.act_evt_log</code>.
     */
    public final ActEvtLog ACT_EVT_LOG = club.ndt.oauth.boot.entity.tables.ActEvtLog.ACT_EVT_LOG;

    /**
     * The table <code>ndt.act_ge_bytearray</code>.
     */
    public final ActGeBytearray ACT_GE_BYTEARRAY = club.ndt.oauth.boot.entity.tables.ActGeBytearray.ACT_GE_BYTEARRAY;

    /**
     * The table <code>ndt.act_ge_property</code>.
     */
    public final ActGeProperty ACT_GE_PROPERTY = club.ndt.oauth.boot.entity.tables.ActGeProperty.ACT_GE_PROPERTY;

    /**
     * The table <code>ndt.act_hi_actinst</code>.
     */
    public final ActHiActinst ACT_HI_ACTINST = club.ndt.oauth.boot.entity.tables.ActHiActinst.ACT_HI_ACTINST;

    /**
     * The table <code>ndt.act_hi_attachment</code>.
     */
    public final ActHiAttachment ACT_HI_ATTACHMENT = club.ndt.oauth.boot.entity.tables.ActHiAttachment.ACT_HI_ATTACHMENT;

    /**
     * The table <code>ndt.act_hi_comment</code>.
     */
    public final ActHiComment ACT_HI_COMMENT = club.ndt.oauth.boot.entity.tables.ActHiComment.ACT_HI_COMMENT;

    /**
     * The table <code>ndt.act_hi_detail</code>.
     */
    public final ActHiDetail ACT_HI_DETAIL = club.ndt.oauth.boot.entity.tables.ActHiDetail.ACT_HI_DETAIL;

    /**
     * The table <code>ndt.act_hi_identitylink</code>.
     */
    public final ActHiIdentitylink ACT_HI_IDENTITYLINK = club.ndt.oauth.boot.entity.tables.ActHiIdentitylink.ACT_HI_IDENTITYLINK;

    /**
     * The table <code>ndt.act_hi_procinst</code>.
     */
    public final ActHiProcinst ACT_HI_PROCINST = club.ndt.oauth.boot.entity.tables.ActHiProcinst.ACT_HI_PROCINST;

    /**
     * The table <code>ndt.act_hi_taskinst</code>.
     */
    public final ActHiTaskinst ACT_HI_TASKINST = club.ndt.oauth.boot.entity.tables.ActHiTaskinst.ACT_HI_TASKINST;

    /**
     * The table <code>ndt.act_hi_varinst</code>.
     */
    public final ActHiVarinst ACT_HI_VARINST = club.ndt.oauth.boot.entity.tables.ActHiVarinst.ACT_HI_VARINST;

    /**
     * The table <code>ndt.act_id_group</code>.
     */
    public final ActIdGroup ACT_ID_GROUP = club.ndt.oauth.boot.entity.tables.ActIdGroup.ACT_ID_GROUP;

    /**
     * The table <code>ndt.act_id_info</code>.
     */
    public final ActIdInfo ACT_ID_INFO = club.ndt.oauth.boot.entity.tables.ActIdInfo.ACT_ID_INFO;

    /**
     * The table <code>ndt.act_id_membership</code>.
     */
    public final ActIdMembership ACT_ID_MEMBERSHIP = club.ndt.oauth.boot.entity.tables.ActIdMembership.ACT_ID_MEMBERSHIP;

    /**
     * The table <code>ndt.act_id_user</code>.
     */
    public final ActIdUser ACT_ID_USER = club.ndt.oauth.boot.entity.tables.ActIdUser.ACT_ID_USER;

    /**
     * The table <code>ndt.act_procdef_info</code>.
     */
    public final ActProcdefInfo ACT_PROCDEF_INFO = club.ndt.oauth.boot.entity.tables.ActProcdefInfo.ACT_PROCDEF_INFO;

    /**
     * The table <code>ndt.act_re_deployment</code>.
     */
    public final ActReDeployment ACT_RE_DEPLOYMENT = club.ndt.oauth.boot.entity.tables.ActReDeployment.ACT_RE_DEPLOYMENT;

    /**
     * The table <code>ndt.act_re_model</code>.
     */
    public final ActReModel ACT_RE_MODEL = club.ndt.oauth.boot.entity.tables.ActReModel.ACT_RE_MODEL;

    /**
     * The table <code>ndt.act_re_procdef</code>.
     */
    public final ActReProcdef ACT_RE_PROCDEF = club.ndt.oauth.boot.entity.tables.ActReProcdef.ACT_RE_PROCDEF;

    /**
     * The table <code>ndt.act_ru_event_subscr</code>.
     */
    public final ActRuEventSubscr ACT_RU_EVENT_SUBSCR = club.ndt.oauth.boot.entity.tables.ActRuEventSubscr.ACT_RU_EVENT_SUBSCR;

    /**
     * The table <code>ndt.act_ru_execution</code>.
     */
    public final ActRuExecution ACT_RU_EXECUTION = club.ndt.oauth.boot.entity.tables.ActRuExecution.ACT_RU_EXECUTION;

    /**
     * The table <code>ndt.act_ru_identitylink</code>.
     */
    public final ActRuIdentitylink ACT_RU_IDENTITYLINK = club.ndt.oauth.boot.entity.tables.ActRuIdentitylink.ACT_RU_IDENTITYLINK;

    /**
     * The table <code>ndt.act_ru_job</code>.
     */
    public final ActRuJob ACT_RU_JOB = club.ndt.oauth.boot.entity.tables.ActRuJob.ACT_RU_JOB;

    /**
     * The table <code>ndt.act_ru_task</code>.
     */
    public final ActRuTask ACT_RU_TASK = club.ndt.oauth.boot.entity.tables.ActRuTask.ACT_RU_TASK;

    /**
     * The table <code>ndt.act_ru_variable</code>.
     */
    public final ActRuVariable ACT_RU_VARIABLE = club.ndt.oauth.boot.entity.tables.ActRuVariable.ACT_RU_VARIABLE;

    /**
     * 行政区划表
     */
    public final CAdminDivision C_ADMIN_DIVISION = club.ndt.oauth.boot.entity.tables.CAdminDivision.C_ADMIN_DIVISION;

    /**
     * 码表映射
     */
    public final CDictMapping C_DICT_MAPPING = club.ndt.oauth.boot.entity.tables.CDictMapping.C_DICT_MAPPING;

    /**
     * 码表类型
     */
    public final CDictType C_DICT_TYPE = club.ndt.oauth.boot.entity.tables.CDictType.C_DICT_TYPE;

    /**
     * 敏感词
     */
    public final CSensitiveWords C_SENSITIVE_WORDS = club.ndt.oauth.boot.entity.tables.CSensitiveWords.C_SENSITIVE_WORDS;

    /**
     * 消息接收者表
     */
    public final MtMessageAccepter MT_MESSAGE_ACCEPTER = club.ndt.oauth.boot.entity.tables.MtMessageAccepter.MT_MESSAGE_ACCEPTER;

    /**
     * 角色菜单中间表
     */
    public final MtRoleMenu MT_ROLE_MENU = club.ndt.oauth.boot.entity.tables.MtRoleMenu.MT_ROLE_MENU;

    /**
     * 用户角色中间表
     */
    public final MtUserRole MT_USER_ROLE = club.ndt.oauth.boot.entity.tables.MtUserRole.MT_USER_ROLE;

    /**
     * The table <code>ndt.oauth_access_token</code>.
     */
    public final OauthAccessToken OAUTH_ACCESS_TOKEN = club.ndt.oauth.boot.entity.tables.OauthAccessToken.OAUTH_ACCESS_TOKEN;

    /**
     * The table <code>ndt.oauth_client_details</code>.
     */
    public final OauthClientDetails OAUTH_CLIENT_DETAILS = club.ndt.oauth.boot.entity.tables.OauthClientDetails.OAUTH_CLIENT_DETAILS;

    /**
     * The table <code>ndt.oauth_code</code>.
     */
    public final OauthCode OAUTH_CODE = club.ndt.oauth.boot.entity.tables.OauthCode.OAUTH_CODE;

    /**
     * The table <code>ndt.oauth_refresh_token</code>.
     */
    public final OauthRefreshToken OAUTH_REFRESH_TOKEN = club.ndt.oauth.boot.entity.tables.OauthRefreshToken.OAUTH_REFRESH_TOKEN;

    /**
     * 散叶广告表
     */
    public final TAdvert T_ADVERT = club.ndt.oauth.boot.entity.tables.TAdvert.T_ADVERT;

    /**
     * 散叶广告表
     */
    public final TAdvertBak T_ADVERT_BAK = club.ndt.oauth.boot.entity.tables.TAdvertBak.T_ADVERT_BAK;

    /**
     * APP版本管理
     */
    public final TAppVersion T_APP_VERSION = club.ndt.oauth.boot.entity.tables.TAppVersion.T_APP_VERSION;

    /**
     * t_banner
     */
    public final TBanner T_BANNER = club.ndt.oauth.boot.entity.tables.TBanner.T_BANNER;

    /**
     * t_banner_bak
     */
    public final TBannerBak T_BANNER_BAK = club.ndt.oauth.boot.entity.tables.TBannerBak.T_BANNER_BAK;

    /**
     * banner弹窗表
     */
    public final TBannerModel T_BANNER_MODEL = club.ndt.oauth.boot.entity.tables.TBannerModel.T_BANNER_MODEL;

    /**
     * 业务资源表
     */
    public final TBusinessResource T_BUSINESS_RESOURCE = club.ndt.oauth.boot.entity.tables.TBusinessResource.T_BUSINESS_RESOURCE;

    /**
     * 表单属性
     */
    public final TButtonForm T_BUTTON_FORM = club.ndt.oauth.boot.entity.tables.TButtonForm.T_BUTTON_FORM;

    /**
     * The table <code>ndt.t_collection</code>.
     */
    public final TCollection T_COLLECTION = club.ndt.oauth.boot.entity.tables.TCollection.T_COLLECTION;

    /**
     * 企业用户信息表
     */
    public final TCompanyDetail T_COMPANY_DETAIL = club.ndt.oauth.boot.entity.tables.TCompanyDetail.T_COMPANY_DETAIL;

    /**
     * 待审核企业信息表
     */
    public final TCompanyDetailPrecheck T_COMPANY_DETAIL_PRECHECK = club.ndt.oauth.boot.entity.tables.TCompanyDetailPrecheck.T_COMPANY_DETAIL_PRECHECK;

    /**
     * 公司年度财务表
     */
    public final TCompanyFinance T_COMPANY_FINANCE = club.ndt.oauth.boot.entity.tables.TCompanyFinance.T_COMPANY_FINANCE;

    /**
     * 公司荣誉资质
     */
    public final TCompanyHonor T_COMPANY_HONOR = club.ndt.oauth.boot.entity.tables.TCompanyHonor.T_COMPANY_HONOR;

    /**
     * 公司参保信息
     */
    public final TCompanyInsurance T_COMPANY_INSURANCE = club.ndt.oauth.boot.entity.tables.TCompanyInsurance.T_COMPANY_INSURANCE;

    /**
     * 公司投资信息
     */
    public final TCompanyInvestment T_COMPANY_INVESTMENT = club.ndt.oauth.boot.entity.tables.TCompanyInvestment.T_COMPANY_INVESTMENT;

    /**
     * 公司经营状况表
     */
    public final TCompanyManagement T_COMPANY_MANAGEMENT = club.ndt.oauth.boot.entity.tables.TCompanyManagement.T_COMPANY_MANAGEMENT;

    /**
     * 公司缴费信息
     */
    public final TCompanyPayment T_COMPANY_PAYMENT = club.ndt.oauth.boot.entity.tables.TCompanyPayment.T_COMPANY_PAYMENT;

    /**
     * The table <code>ndt.t_company_unbind_pre_check</code>.
     */
    public final TCompanyUnbindPreCheck T_COMPANY_UNBIND_PRE_CHECK = club.ndt.oauth.boot.entity.tables.TCompanyUnbindPreCheck.T_COMPANY_UNBIND_PRE_CHECK;

    /**
     * 内容审核表
     */
    public final TContentCheck T_CONTENT_CHECK = club.ndt.oauth.boot.entity.tables.TContentCheck.T_CONTENT_CHECK;

    /**
     * 合作社信息表
     */
    public final TCooperation T_COOPERATION = club.ndt.oauth.boot.entity.tables.TCooperation.T_COOPERATION;

    /**
     * The table <code>ndt.t_credit_division</code>.
     */
    public final TCreditDivision T_CREDIT_DIVISION = club.ndt.oauth.boot.entity.tables.TCreditDivision.T_CREDIT_DIVISION;

    /**
     * 信用评定汇总表
     */
    public final TCreditRating T_CREDIT_RATING = club.ndt.oauth.boot.entity.tables.TCreditRating.T_CREDIT_RATING;

    /**
     * 信用任务设置
     */
    public final TCreditTask T_CREDIT_TASK = club.ndt.oauth.boot.entity.tables.TCreditTask.T_CREDIT_TASK;

    /**
     * 贴息申请信息
     */
    public final TDiscountBaseInfo T_DISCOUNT_BASE_INFO = club.ndt.oauth.boot.entity.tables.TDiscountBaseInfo.T_DISCOUNT_BASE_INFO;

    /**
     * 村站采集信息
     */
    public final TDiscountCollection T_DISCOUNT_COLLECTION = club.ndt.oauth.boot.entity.tables.TDiscountCollection.T_DISCOUNT_COLLECTION;

    /**
     * 各个区县贴息比例
     */
    public final TDiscountScaleInfo T_DISCOUNT_SCALE_INFO = club.ndt.oauth.boot.entity.tables.TDiscountScaleInfo.T_DISCOUNT_SCALE_INFO;

    /**
     * 申请流程同步表
     */
    public final TDiscountSync T_DISCOUNT_SYNC = club.ndt.oauth.boot.entity.tables.TDiscountSync.T_DISCOUNT_SYNC;

    /**
     * 农场
     */
    public final TFarm T_FARM = club.ndt.oauth.boot.entity.tables.TFarm.T_FARM;

    /**
     * 文件表
     */
    public final TFile T_FILE = club.ndt.oauth.boot.entity.tables.TFile.T_FILE;

    /**
     * The table <code>ndt.t_financial_apply</code>.
     */
    public final TFinancialApply T_FINANCIAL_APPLY = club.ndt.oauth.boot.entity.tables.TFinancialApply.T_FINANCIAL_APPLY;

    /**
     * The table <code>ndt.t_financial_sync</code>.
     */
    public final TFinancialSync T_FINANCIAL_SYNC = club.ndt.oauth.boot.entity.tables.TFinancialSync.T_FINANCIAL_SYNC;

    /**
     * 资讯表
     */
    public final TInfo T_INFO = club.ndt.oauth.boot.entity.tables.TInfo.T_INFO;

    /**
     * 资讯表
     */
    public final TInfoWeb T_INFO_WEB = club.ndt.oauth.boot.entity.tables.TInfoWeb.T_INFO_WEB;

    /**
     * 保险信贷订单
     */
    public final TInsureLoanOrder T_INSURE_LOAN_ORDER = club.ndt.oauth.boot.entity.tables.TInsureLoanOrder.T_INSURE_LOAN_ORDER;

    /**
     * 保险信贷产品
     */
    public final TInsureLoanProduct T_INSURE_LOAN_PRODUCT = club.ndt.oauth.boot.entity.tables.TInsureLoanProduct.T_INSURE_LOAN_PRODUCT;

    /**
     * 保险信贷轨迹表
     */
    public final TInsureLoanTrace T_INSURE_LOAN_TRACE = club.ndt.oauth.boot.entity.tables.TInsureLoanTrace.T_INSURE_LOAN_TRACE;

    /**
     * 保险订单
     */
    public final TInsureOrder T_INSURE_ORDER = club.ndt.oauth.boot.entity.tables.TInsureOrder.T_INSURE_ORDER;

    /**
     * 保险产品
     */
    public final TInsureProduct T_INSURE_PRODUCT = club.ndt.oauth.boot.entity.tables.TInsureProduct.T_INSURE_PRODUCT;

    /**
     * 积分规则表
     */
    public final TIntegralRule T_INTEGRAL_RULE = club.ndt.oauth.boot.entity.tables.TIntegralRule.T_INTEGRAL_RULE;

    /**
     * 种养大户
     */
    public final TLargeBreeder T_LARGE_BREEDER = club.ndt.oauth.boot.entity.tables.TLargeBreeder.T_LARGE_BREEDER;

    /**
     * 龙头企业信息表
     */
    public final TLeadingEnterprise T_LEADING_ENTERPRISE = club.ndt.oauth.boot.entity.tables.TLeadingEnterprise.T_LEADING_ENTERPRISE;

    /**
     * 贷款申请
     */
    public final TLoanApply T_LOAN_APPLY = club.ndt.oauth.boot.entity.tables.TLoanApply.T_LOAN_APPLY;

    /**
     * The table <code>ndt.t_loan_apply_pond</code>.
     */
    public final TLoanApplyPond T_LOAN_APPLY_POND = club.ndt.oauth.boot.entity.tables.TLoanApplyPond.T_LOAN_APPLY_POND;

    /**
     * 贷款成交记录
     */
    public final TLoanDone T_LOAN_DONE = club.ndt.oauth.boot.entity.tables.TLoanDone.T_LOAN_DONE;

    /**
     * 贷款担保中间表
     */
    public final TLoanGuarantee T_LOAN_GUARANTEE = club.ndt.oauth.boot.entity.tables.TLoanGuarantee.T_LOAN_GUARANTEE;

    /**
     * 好人贷申请
     */
    public final TLoanHaorenApply T_LOAN_HAOREN_APPLY = club.ndt.oauth.boot.entity.tables.TLoanHaorenApply.T_LOAN_HAOREN_APPLY;

    /**
     * T_LOAN_INVITATION
     */
    public final TLoanInvitation T_LOAN_INVITATION = club.ndt.oauth.boot.entity.tables.TLoanInvitation.T_LOAN_INVITATION;

    /**
     * 贷款逾期
     */
    public final TLoanOverdue T_LOAN_OVERDUE = club.ndt.oauth.boot.entity.tables.TLoanOverdue.T_LOAN_OVERDUE;

    /**
     * 贷款还款表
     */
    public final TLoanPayoff T_LOAN_PAYOFF = club.ndt.oauth.boot.entity.tables.TLoanPayoff.T_LOAN_PAYOFF;

    /**
     * 贷款产品
     */
    public final TLoanProduct T_LOAN_PRODUCT = club.ndt.oauth.boot.entity.tables.TLoanProduct.T_LOAN_PRODUCT;

    /**
     * The table <code>ndt.t_loan_product_annex</code>.
     */
    public final TLoanProductAnnex T_LOAN_PRODUCT_ANNEX = club.ndt.oauth.boot.entity.tables.TLoanProductAnnex.T_LOAN_PRODUCT_ANNEX;

    /**
     * The table <code>ndt.t_loan_product_cost_info</code>.
     */
    public final TLoanProductCostInfo T_LOAN_PRODUCT_COST_INFO = club.ndt.oauth.boot.entity.tables.TLoanProductCostInfo.T_LOAN_PRODUCT_COST_INFO;

    /**
     * The table <code>ndt.t_loan_product_data_info</code>.
     */
    public final TLoanProductDataInfo T_LOAN_PRODUCT_DATA_INFO = club.ndt.oauth.boot.entity.tables.TLoanProductDataInfo.T_LOAN_PRODUCT_DATA_INFO;

    /**
     * The table <code>ndt.t_loan_raid_bs</code>.
     */
    public final TLoanRaidBs T_LOAN_RAID_BS = club.ndt.oauth.boot.entity.tables.TLoanRaidBs.T_LOAN_RAID_BS;

    /**
     * 放款记录
     */
    public final TLoanRecord T_LOAN_RECORD = club.ndt.oauth.boot.entity.tables.TLoanRecord.T_LOAN_RECORD;

    /**
     * The table <code>ndt.t_loan_term</code>.
     */
    public final TLoanTerm T_LOAN_TERM = club.ndt.oauth.boot.entity.tables.TLoanTerm.T_LOAN_TERM;

    /**
     * 贷款流程同步表
     */
    public final TLoanflowSync T_LOANFLOW_SYNC = club.ndt.oauth.boot.entity.tables.TLoanflowSync.T_LOANFLOW_SYNC;

    /**
     * 贷款产品同步配置表
     */
    public final TLoanproductSyncconfig T_LOANPRODUCT_SYNCCONFIG = club.ndt.oauth.boot.entity.tables.TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG;

    /**
     * 用户登录日志表
     */
    public final TLoginLog T_LOGIN_LOG = club.ndt.oauth.boot.entity.tables.TLoginLog.T_LOGIN_LOG;

    /**
     * 抽奖记录表
     */
    public final TLotteryRecord T_LOTTERY_RECORD = club.ndt.oauth.boot.entity.tables.TLotteryRecord.T_LOTTERY_RECORD;

    /**
     * 重点支持项目表
     */
    public final TMajorProject T_MAJOR_PROJECT = club.ndt.oauth.boot.entity.tables.TMajorProject.T_MAJOR_PROJECT;

    /**
     * 菜单表
     */
    public final TMenu T_MENU = club.ndt.oauth.boot.entity.tables.TMenu.T_MENU;

    /**
     * 消息表
     */
    public final TMessage T_MESSAGE = club.ndt.oauth.boot.entity.tables.TMessage.T_MESSAGE;

    /**
     * 国债网点表
     */
    public final TNationalDebtDots T_NATIONAL_DEBT_DOTS = club.ndt.oauth.boot.entity.tables.TNationalDebtDots.T_NATIONAL_DEBT_DOTS;

    /**
     * 国债网点表
     */
    public final TNationalDebtDotsCopy1 T_NATIONAL_DEBT_DOTS_COPY1 = club.ndt.oauth.boot.entity.tables.TNationalDebtDotsCopy1.T_NATIONAL_DEBT_DOTS_COPY1;

    /**
     * 国债产品
     */
    public final TNationalDebtOrders T_NATIONAL_DEBT_ORDERS = club.ndt.oauth.boot.entity.tables.TNationalDebtOrders.T_NATIONAL_DEBT_ORDERS;

    /**
     * The table <code>ndt.t_national_debt_product</code>.
     */
    public final TNationalDebtProduct T_NATIONAL_DEBT_PRODUCT = club.ndt.oauth.boot.entity.tables.TNationalDebtProduct.T_NATIONAL_DEBT_PRODUCT;

    /**
     * 国债产品期限
     */
    public final TNationalDebtTerm T_NATIONAL_DEBT_TERM = club.ndt.oauth.boot.entity.tables.TNationalDebtTerm.T_NATIONAL_DEBT_TERM;

    /**
     * 用户操作日志表
     */
    public final TOperLog T_OPER_LOG = club.ndt.oauth.boot.entity.tables.TOperLog.T_OPER_LOG;

    /**
     * 订单详情表
     */
    public final TOrderDetail T_ORDER_DETAIL = club.ndt.oauth.boot.entity.tables.TOrderDetail.T_ORDER_DETAIL;

    /**
     * 订单信息表
     */
    public final TOrderInfo T_ORDER_INFO = club.ndt.oauth.boot.entity.tables.TOrderInfo.T_ORDER_INFO;

    /**
     * 组织机构表
     */
    public final TOrg T_ORG = club.ndt.oauth.boot.entity.tables.TOrg.T_ORG;

    /**
     * 个人公司账号绑定表
     */
    public final TPersonCompanyRel T_PERSON_COMPANY_REL = club.ndt.oauth.boot.entity.tables.TPersonCompanyRel.T_PERSON_COMPANY_REL;

    /**
     * 个人公司账号绑定表
     */
    public final TPersonCompanyUnbindRel T_PERSON_COMPANY_UNBIND_REL = club.ndt.oauth.boot.entity.tables.TPersonCompanyUnbindRel.T_PERSON_COMPANY_UNBIND_REL;

    /**
     * 个人用户详情表
     */
    public final TPersonalDetail T_PERSONAL_DETAIL = club.ndt.oauth.boot.entity.tables.TPersonalDetail.T_PERSONAL_DETAIL;

    /**
     * 政策表
     */
    public final TPolicy T_POLICY = club.ndt.oauth.boot.entity.tables.TPolicy.T_POLICY;

    /**
     * 政策服务
     */
    public final TPolicyService T_POLICY_SERVICE = club.ndt.oauth.boot.entity.tables.TPolicyService.T_POLICY_SERVICE;

    /**
     * 政策服务申请
     */
    public final TPolicyServiceApply T_POLICY_SERVICE_APPLY = club.ndt.oauth.boot.entity.tables.TPolicyServiceApply.T_POLICY_SERVICE_APPLY;

    /**
     * 政策服务用户申请资料
     */
    public final TPolicyServiceMaterial T_POLICY_SERVICE_MATERIAL = club.ndt.oauth.boot.entity.tables.TPolicyServiceMaterial.T_POLICY_SERVICE_MATERIAL;

    /**
     * 政策申办统计基数
     */
    public final TPolicyServiceRadix T_POLICY_SERVICE_RADIX = club.ndt.oauth.boot.entity.tables.TPolicyServiceRadix.T_POLICY_SERVICE_RADIX;

    /**
     * 政策服务流程处理
     */
    public final TPolicyServiceSync T_POLICY_SERVICE_SYNC = club.ndt.oauth.boot.entity.tables.TPolicyServiceSync.T_POLICY_SERVICE_SYNC;

    /**
     * 农业职业经纪人
     */
    public final TProfessionAgent T_PROFESSION_AGENT = club.ndt.oauth.boot.entity.tables.TProfessionAgent.T_PROFESSION_AGENT;

    /**
     * The table <code>ndt.t_property_rights_trading</code>.
     */
    public final TPropertyRightsTrading T_PROPERTY_RIGHTS_TRADING = club.ndt.oauth.boot.entity.tables.TPropertyRightsTrading.T_PROPERTY_RIGHTS_TRADING;

    /**
     * 二维码扫码推广注册详细信息
     */
    public final TQrCodeInfo T_QR_CODE_INFO = club.ndt.oauth.boot.entity.tables.TQrCodeInfo.T_QR_CODE_INFO;

    /**
     * The table <code>ndt.t_questionnaire</code>.
     */
    public final TQuestionnaire T_QUESTIONNAIRE = club.ndt.oauth.boot.entity.tables.TQuestionnaire.T_QUESTIONNAIRE;

    /**
     * 推荐表
     */
    public final TRecommendation T_RECOMMENDATION = club.ndt.oauth.boot.entity.tables.TRecommendation.T_RECOMMENDATION;

    /**
     * The table <code>ndt.t_risks_share</code>.
     */
    public final TRisksShare T_RISKS_SHARE = club.ndt.oauth.boot.entity.tables.TRisksShare.T_RISKS_SHARE;

    /**
     * The table <code>ndt.t_risks_share_trace</code>.
     */
    public final TRisksShareTrace T_RISKS_SHARE_TRACE = club.ndt.oauth.boot.entity.tables.TRisksShareTrace.T_RISKS_SHARE_TRACE;

    /**
     * 风险分担申请
     */
    public final TRiskshareApply T_RISKSHARE_APPLY = club.ndt.oauth.boot.entity.tables.TRiskshareApply.T_RISKSHARE_APPLY;

    /**
     * 风险分担申请处理
     */
    public final TRiskshareApplyProcess T_RISKSHARE_APPLY_PROCESS = club.ndt.oauth.boot.entity.tables.TRiskshareApplyProcess.T_RISKSHARE_APPLY_PROCESS;

    /**
     * 风险分担结果
     */
    public final TRiskshareDone T_RISKSHARE_DONE = club.ndt.oauth.boot.entity.tables.TRiskshareDone.T_RISKSHARE_DONE;

    /**
     * 角色表
     */
    public final TRole T_ROLE = club.ndt.oauth.boot.entity.tables.TRole.T_ROLE;

    /**
     * The table <code>ndt.t_score_trace</code>.
     */
    public final TScoreTrace T_SCORE_TRACE = club.ndt.oauth.boot.entity.tables.TScoreTrace.T_SCORE_TRACE;

    /**
     * 商品系统表
     */
    public final TShopWare T_SHOP_WARE = club.ndt.oauth.boot.entity.tables.TShopWare.T_SHOP_WARE;

    /**
     * 商品图片详情表
     */
    public final TShopWareInfo T_SHOP_WARE_INFO = club.ndt.oauth.boot.entity.tables.TShopWareInfo.T_SHOP_WARE_INFO;

    /**
     * 签到记录表
     */
    public final TSignRecord T_SIGN_RECORD = club.ndt.oauth.boot.entity.tables.TSignRecord.T_SIGN_RECORD;

    /**
     * 站内消息表
     */
    public final TSiteMessage T_SITE_MESSAGE = club.ndt.oauth.boot.entity.tables.TSiteMessage.T_SITE_MESSAGE;

    /**
     * 小V贷款订单
     */
    public final TSmallLoanOrder T_SMALL_LOAN_ORDER = club.ndt.oauth.boot.entity.tables.TSmallLoanOrder.T_SMALL_LOAN_ORDER;

    /**
     * 小V产品
     */
    public final TSmallLoanProduct T_SMALL_LOAN_PRODUCT = club.ndt.oauth.boot.entity.tables.TSmallLoanProduct.T_SMALL_LOAN_PRODUCT;

    /**
     * 小V贷款轨迹表
     */
    public final TSmallLoanTrace T_SMALL_LOAN_TRACE = club.ndt.oauth.boot.entity.tables.TSmallLoanTrace.T_SMALL_LOAN_TRACE;

    /**
     * 短消息表
     */
    public final TSms T_SMS = club.ndt.oauth.boot.entity.tables.TSms.T_SMS;

    /**
     * 基准利率变化时间区间 
     */
    public final TStandardRate T_STANDARD_RATE = club.ndt.oauth.boot.entity.tables.TStandardRate.T_STANDARD_RATE;

    /**
     * 静态资源对应fastdfs表
     */
    public final TStaticSource T_STATIC_SOURCE = club.ndt.oauth.boot.entity.tables.TStaticSource.T_STATIC_SOURCE;

    /**
     * 静态资源对应fastdfs表
     */
    public final TStaticSourceBak T_STATIC_SOURCE_BAK = club.ndt.oauth.boot.entity.tables.TStaticSourceBak.T_STATIC_SOURCE_BAK;

    /**
     * 步骤主表
     */
    public final TStepBase T_STEP_BASE = club.ndt.oauth.boot.entity.tables.TStepBase.T_STEP_BASE;

    /**
     * 步骤操作按钮
     */
    public final TStepButton T_STEP_BUTTON = club.ndt.oauth.boot.entity.tables.TStepButton.T_STEP_BUTTON;

    /**
     * 项目大类型
     */
    public final TTermBase T_TERM_BASE = club.ndt.oauth.boot.entity.tables.TTermBase.T_TERM_BASE;

    /**
     * 第三方用户表
     */
    public final TThirdUser T_THIRD_USER = club.ndt.oauth.boot.entity.tables.TThirdUser.T_THIRD_USER;

    /**
     * 用户表
     */
    public final TUser T_USER = club.ndt.oauth.boot.entity.tables.TUser.T_USER;

    /**
     * 用户信用分数
     */
    public final TUserCredit T_USER_CREDIT = club.ndt.oauth.boot.entity.tables.TUserCredit.T_USER_CREDIT;

    /**
     * 用户信用任务日志
     */
    public final TUserCredittaskLog T_USER_CREDITTASK_LOG = club.ndt.oauth.boot.entity.tables.TUserCredittaskLog.T_USER_CREDITTASK_LOG;

    /**
     * 用户详细数据
     */
    public final TUserInfoDetail T_USER_INFO_DETAIL = club.ndt.oauth.boot.entity.tables.TUserInfoDetail.T_USER_INFO_DETAIL;

    /**
     * 用户产权表
     */
    public final TUserPropertyright T_USER_PROPERTYRIGHT = club.ndt.oauth.boot.entity.tables.TUserPropertyright.T_USER_PROPERTYRIGHT;

    /**
     * 村站采集的公司信息
     */
    public final TVillageCompanyBaseinfo T_VILLAGE_COMPANY_BASEINFO = club.ndt.oauth.boot.entity.tables.TVillageCompanyBaseinfo.T_VILLAGE_COMPANY_BASEINFO;

    /**
     * 村站采集的公司经营信息
     */
    public final TVillageCompanyBusiness T_VILLAGE_COMPANY_BUSINESS = club.ndt.oauth.boot.entity.tables.TVillageCompanyBusiness.T_VILLAGE_COMPANY_BUSINESS;

    /**
     * 村站采集的公司信用称号信息
     */
    public final TVillageCompanyCredit T_VILLAGE_COMPANY_CREDIT = club.ndt.oauth.boot.entity.tables.TVillageCompanyCredit.T_VILLAGE_COMPANY_CREDIT;

    /**
     * 村站采集的公司信息
     */
    public final TVillageCompanyDetail T_VILLAGE_COMPANY_DETAIL = club.ndt.oauth.boot.entity.tables.TVillageCompanyDetail.T_VILLAGE_COMPANY_DETAIL;

    /**
     * 村站采集的公司用工信息
     */
    public final TVillageCompanyEmployment T_VILLAGE_COMPANY_EMPLOYMENT = club.ndt.oauth.boot.entity.tables.TVillageCompanyEmployment.T_VILLAGE_COMPANY_EMPLOYMENT;

    /**
     * 村站采集的公司信用评价信息
     */
    public final TVillageCompanyEvaluation T_VILLAGE_COMPANY_EVALUATION = club.ndt.oauth.boot.entity.tables.TVillageCompanyEvaluation.T_VILLAGE_COMPANY_EVALUATION;

    /**
     * 村站采集的公司年度财务表
     */
    public final TVillageCompanyFinance T_VILLAGE_COMPANY_FINANCE = club.ndt.oauth.boot.entity.tables.TVillageCompanyFinance.T_VILLAGE_COMPANY_FINANCE;

    /**
     * 村站采集的公司荣誉资质
     */
    public final TVillageCompanyHonor T_VILLAGE_COMPANY_HONOR = club.ndt.oauth.boot.entity.tables.TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR;

    /**
     * 村站采集的公司参保信息
     */
    public final TVillageCompanyInsurance T_VILLAGE_COMPANY_INSURANCE = club.ndt.oauth.boot.entity.tables.TVillageCompanyInsurance.T_VILLAGE_COMPANY_INSURANCE;

    /**
     * 村站采集的公司投资信息
     */
    public final TVillageCompanyInvestment T_VILLAGE_COMPANY_INVESTMENT = club.ndt.oauth.boot.entity.tables.TVillageCompanyInvestment.T_VILLAGE_COMPANY_INVESTMENT;

    /**
     * 村站采集的公司知识产权信息
     */
    public final TVillageCompanyKnowledge T_VILLAGE_COMPANY_KNOWLEDGE = club.ndt.oauth.boot.entity.tables.TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE;

    /**
     * 村站采集的公司贷款信息
     */
    public final TVillageCompanyLoan T_VILLAGE_COMPANY_LOAN = club.ndt.oauth.boot.entity.tables.TVillageCompanyLoan.T_VILLAGE_COMPANY_LOAN;

    /**
     * 村站采集的公司经营状况表
     */
    public final TVillageCompanyManagement T_VILLAGE_COMPANY_MANAGEMENT = club.ndt.oauth.boot.entity.tables.TVillageCompanyManagement.T_VILLAGE_COMPANY_MANAGEMENT;

    /**
     * 村站采集的公司专利资质信息
     */
    public final TVillageCompanyPatent T_VILLAGE_COMPANY_PATENT = club.ndt.oauth.boot.entity.tables.TVillageCompanyPatent.T_VILLAGE_COMPANY_PATENT;

    /**
     * 村站采集的公司缴费信息
     */
    public final TVillageCompanyPayment T_VILLAGE_COMPANY_PAYMENT = club.ndt.oauth.boot.entity.tables.TVillageCompanyPayment.T_VILLAGE_COMPANY_PAYMENT;

    /**
     * 村站采集的公司采购信息
     */
    public final TVillageCompanyPurchase T_VILLAGE_COMPANY_PURCHASE = club.ndt.oauth.boot.entity.tables.TVillageCompanyPurchase.T_VILLAGE_COMPANY_PURCHASE;

    /**
     * 村站采集的公司奖励/处罚信息
     */
    public final TVillageCompanyReward T_VILLAGE_COMPANY_REWARD = club.ndt.oauth.boot.entity.tables.TVillageCompanyReward.T_VILLAGE_COMPANY_REWARD;

    /**
     * 村站采集的公司销售信息
     */
    public final TVillageCompanySales T_VILLAGE_COMPANY_SALES = club.ndt.oauth.boot.entity.tables.TVillageCompanySales.T_VILLAGE_COMPANY_SALES;

    /**
     * 村站采集的公司政府补贴信息
     */
    public final TVillageCompanySubsidy T_VILLAGE_COMPANY_SUBSIDY = club.ndt.oauth.boot.entity.tables.TVillageCompanySubsidy.T_VILLAGE_COMPANY_SUBSIDY;

    /**
     * 村站采集的公司权证信息
     */
    public final TVillageCompanyWarrant T_VILLAGE_COMPANY_WARRANT = club.ndt.oauth.boot.entity.tables.TVillageCompanyWarrant.T_VILLAGE_COMPANY_WARRANT;

    /**
     * 奖惩信息
     */
    public final TVillagePersonalAwardsPunishments T_VILLAGE_PERSONAL_AWARDS_PUNISHMENTS = club.ndt.oauth.boot.entity.tables.TVillagePersonalAwardsPunishments.T_VILLAGE_PERSONAL_AWARDS_PUNISHMENTS;

    /**
     * 农业信用基础信息
     */
    public final TVillagePersonalBaseinfo T_VILLAGE_PERSONAL_BASEINFO = club.ndt.oauth.boot.entity.tables.TVillagePersonalBaseinfo.T_VILLAGE_PERSONAL_BASEINFO;

    /**
     * 非生产性车辆信息
     */
    public final TVillagePersonalCarinfo T_VILLAGE_PERSONAL_CARINFO = club.ndt.oauth.boot.entity.tables.TVillagePersonalCarinfo.T_VILLAGE_PERSONAL_CARINFO;

    /**
     * 信用评价信息
     */
    public final TVillagePersonalCreditRating T_VILLAGE_PERSONAL_CREDIT_RATING = club.ndt.oauth.boot.entity.tables.TVillagePersonalCreditRating.T_VILLAGE_PERSONAL_CREDIT_RATING;

    /**
     * 信用称号信息
     */
    public final TVillagePersonalCreditTitle T_VILLAGE_PERSONAL_CREDIT_TITLE = club.ndt.oauth.boot.entity.tables.TVillagePersonalCreditTitle.T_VILLAGE_PERSONAL_CREDIT_TITLE;

    /**
     * 村站个人信息采集表
     */
    public final TVillagePersonalDetail T_VILLAGE_PERSONAL_DETAIL = club.ndt.oauth.boot.entity.tables.TVillagePersonalDetail.T_VILLAGE_PERSONAL_DETAIL;

    /**
     * 设备信息
     */
    public final TVillagePersonalEquipment T_VILLAGE_PERSONAL_EQUIPMENT = club.ndt.oauth.boot.entity.tables.TVillagePersonalEquipment.T_VILLAGE_PERSONAL_EQUIPMENT;

    /**
     * 房屋资产信息
     */
    public final TVillagePersonalHouse T_VILLAGE_PERSONAL_HOUSE = club.ndt.oauth.boot.entity.tables.TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE;

    /**
     * 政策性保险参保信息
     */
    public final TVillagePersonalInsured T_VILLAGE_PERSONAL_INSURED = club.ndt.oauth.boot.entity.tables.TVillagePersonalInsured.T_VILLAGE_PERSONAL_INSURED;

    /**
     * 个人其他信息
     */
    public final TVillagePersonalOtherinfo T_VILLAGE_PERSONAL_OTHERINFO = club.ndt.oauth.boot.entity.tables.TVillagePersonalOtherinfo.T_VILLAGE_PERSONAL_OTHERINFO;

    /**
     * 专利资质信息
     */
    public final TVillagePersonalPatent T_VILLAGE_PERSONAL_PATENT = club.ndt.oauth.boot.entity.tables.TVillagePersonalPatent.T_VILLAGE_PERSONAL_PATENT;

    /**
     * 水电气费缴费情况
     */
    public final TVillagePersonalPayment T_VILLAGE_PERSONAL_PAYMENT = club.ndt.oauth.boot.entity.tables.TVillagePersonalPayment.T_VILLAGE_PERSONAL_PAYMENT;

    /**
     * 生产资料信息
     */
    public final TVillagePersonalProductioninfo T_VILLAGE_PERSONAL_PRODUCTIONINFO = club.ndt.oauth.boot.entity.tables.TVillagePersonalProductioninfo.T_VILLAGE_PERSONAL_PRODUCTIONINFO;

    /**
     * 采购信息
     */
    public final TVillagePersonalPurchasing T_VILLAGE_PERSONAL_PURCHASING = club.ndt.oauth.boot.entity.tables.TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING;

    /**
     * 用工信息
     */
    public final TVillagePersonalRecruitment T_VILLAGE_PERSONAL_RECRUITMENT = club.ndt.oauth.boot.entity.tables.TVillagePersonalRecruitment.T_VILLAGE_PERSONAL_RECRUITMENT;

    /**
     * 获得相关权证情况信息
     */
    public final TVillagePersonalWarrantinfo T_VILLAGE_PERSONAL_WARRANTINFO = club.ndt.oauth.boot.entity.tables.TVillagePersonalWarrantinfo.T_VILLAGE_PERSONAL_WARRANTINFO;

    /**
     * The table <code>ndt.v_statistics_user</code>.
     */
    public final VStatisticsUser V_STATISTICS_USER = club.ndt.oauth.boot.entity.tables.VStatisticsUser.V_STATISTICS_USER;

    /**
     * No further instances allowed
     */
    private Ndt() {
        super("ndt", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Sequence<?>> getSequences() {
        List result = new ArrayList();
        result.addAll(getSequences0());
        return result;
    }

    private final List<Sequence<?>> getSequences0() {
        return Arrays.<Sequence<?>>asList(
            Sequences.ACT_EVT_LOG_LOG_NR__SEQ,
            Sequences.SEQ1,
            Sequences.TB_FARM0_COPY_DATE,
            Sequences.TB_INFO_COPY_DATE,
            Sequences.TB_LOAN_DONE_RECORD_SEQ,
            Sequences.TB_MAJOR_SEQ,
            Sequences.TB_USER_DETAIL_ID_SEQ,
            Sequences.T_RISKS_SHARE_ID_SEQ,
            Sequences.T_RISKS_SHARE_TRACE_ID_SEQ);
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            ActEvtLog.ACT_EVT_LOG,
            ActGeBytearray.ACT_GE_BYTEARRAY,
            ActGeProperty.ACT_GE_PROPERTY,
            ActHiActinst.ACT_HI_ACTINST,
            ActHiAttachment.ACT_HI_ATTACHMENT,
            ActHiComment.ACT_HI_COMMENT,
            ActHiDetail.ACT_HI_DETAIL,
            ActHiIdentitylink.ACT_HI_IDENTITYLINK,
            ActHiProcinst.ACT_HI_PROCINST,
            ActHiTaskinst.ACT_HI_TASKINST,
            ActHiVarinst.ACT_HI_VARINST,
            ActIdGroup.ACT_ID_GROUP,
            ActIdInfo.ACT_ID_INFO,
            ActIdMembership.ACT_ID_MEMBERSHIP,
            ActIdUser.ACT_ID_USER,
            ActProcdefInfo.ACT_PROCDEF_INFO,
            ActReDeployment.ACT_RE_DEPLOYMENT,
            ActReModel.ACT_RE_MODEL,
            ActReProcdef.ACT_RE_PROCDEF,
            ActRuEventSubscr.ACT_RU_EVENT_SUBSCR,
            ActRuExecution.ACT_RU_EXECUTION,
            ActRuIdentitylink.ACT_RU_IDENTITYLINK,
            ActRuJob.ACT_RU_JOB,
            ActRuTask.ACT_RU_TASK,
            ActRuVariable.ACT_RU_VARIABLE,
            CAdminDivision.C_ADMIN_DIVISION,
            CDictMapping.C_DICT_MAPPING,
            CDictType.C_DICT_TYPE,
            CSensitiveWords.C_SENSITIVE_WORDS,
            MtMessageAccepter.MT_MESSAGE_ACCEPTER,
            MtRoleMenu.MT_ROLE_MENU,
            MtUserRole.MT_USER_ROLE,
            OauthAccessToken.OAUTH_ACCESS_TOKEN,
            OauthClientDetails.OAUTH_CLIENT_DETAILS,
            OauthCode.OAUTH_CODE,
            OauthRefreshToken.OAUTH_REFRESH_TOKEN,
            TAdvert.T_ADVERT,
            TAdvertBak.T_ADVERT_BAK,
            TAppVersion.T_APP_VERSION,
            TBanner.T_BANNER,
            TBannerBak.T_BANNER_BAK,
            TBannerModel.T_BANNER_MODEL,
            TBusinessResource.T_BUSINESS_RESOURCE,
            TButtonForm.T_BUTTON_FORM,
            TCollection.T_COLLECTION,
            TCompanyDetail.T_COMPANY_DETAIL,
            TCompanyDetailPrecheck.T_COMPANY_DETAIL_PRECHECK,
            TCompanyFinance.T_COMPANY_FINANCE,
            TCompanyHonor.T_COMPANY_HONOR,
            TCompanyInsurance.T_COMPANY_INSURANCE,
            TCompanyInvestment.T_COMPANY_INVESTMENT,
            TCompanyManagement.T_COMPANY_MANAGEMENT,
            TCompanyPayment.T_COMPANY_PAYMENT,
            TCompanyUnbindPreCheck.T_COMPANY_UNBIND_PRE_CHECK,
            TContentCheck.T_CONTENT_CHECK,
            TCooperation.T_COOPERATION,
            TCreditDivision.T_CREDIT_DIVISION,
            TCreditRating.T_CREDIT_RATING,
            TCreditTask.T_CREDIT_TASK,
            TDiscountBaseInfo.T_DISCOUNT_BASE_INFO,
            TDiscountCollection.T_DISCOUNT_COLLECTION,
            TDiscountScaleInfo.T_DISCOUNT_SCALE_INFO,
            TDiscountSync.T_DISCOUNT_SYNC,
            TFarm.T_FARM,
            TFile.T_FILE,
            TFinancialApply.T_FINANCIAL_APPLY,
            TFinancialSync.T_FINANCIAL_SYNC,
            TInfo.T_INFO,
            TInfoWeb.T_INFO_WEB,
            TInsureLoanOrder.T_INSURE_LOAN_ORDER,
            TInsureLoanProduct.T_INSURE_LOAN_PRODUCT,
            TInsureLoanTrace.T_INSURE_LOAN_TRACE,
            TInsureOrder.T_INSURE_ORDER,
            TInsureProduct.T_INSURE_PRODUCT,
            TIntegralRule.T_INTEGRAL_RULE,
            TLargeBreeder.T_LARGE_BREEDER,
            TLeadingEnterprise.T_LEADING_ENTERPRISE,
            TLoanApply.T_LOAN_APPLY,
            TLoanApplyPond.T_LOAN_APPLY_POND,
            TLoanDone.T_LOAN_DONE,
            TLoanGuarantee.T_LOAN_GUARANTEE,
            TLoanHaorenApply.T_LOAN_HAOREN_APPLY,
            TLoanInvitation.T_LOAN_INVITATION,
            TLoanOverdue.T_LOAN_OVERDUE,
            TLoanPayoff.T_LOAN_PAYOFF,
            TLoanProduct.T_LOAN_PRODUCT,
            TLoanProductAnnex.T_LOAN_PRODUCT_ANNEX,
            TLoanProductCostInfo.T_LOAN_PRODUCT_COST_INFO,
            TLoanProductDataInfo.T_LOAN_PRODUCT_DATA_INFO,
            TLoanRaidBs.T_LOAN_RAID_BS,
            TLoanRecord.T_LOAN_RECORD,
            TLoanTerm.T_LOAN_TERM,
            TLoanflowSync.T_LOANFLOW_SYNC,
            TLoanproductSyncconfig.T_LOANPRODUCT_SYNCCONFIG,
            TLoginLog.T_LOGIN_LOG,
            TLotteryRecord.T_LOTTERY_RECORD,
            TMajorProject.T_MAJOR_PROJECT,
            TMenu.T_MENU,
            TMessage.T_MESSAGE,
            TNationalDebtDots.T_NATIONAL_DEBT_DOTS,
            TNationalDebtDotsCopy1.T_NATIONAL_DEBT_DOTS_COPY1,
            TNationalDebtOrders.T_NATIONAL_DEBT_ORDERS,
            TNationalDebtProduct.T_NATIONAL_DEBT_PRODUCT,
            TNationalDebtTerm.T_NATIONAL_DEBT_TERM,
            TOperLog.T_OPER_LOG,
            TOrderDetail.T_ORDER_DETAIL,
            TOrderInfo.T_ORDER_INFO,
            TOrg.T_ORG,
            TPersonCompanyRel.T_PERSON_COMPANY_REL,
            TPersonCompanyUnbindRel.T_PERSON_COMPANY_UNBIND_REL,
            TPersonalDetail.T_PERSONAL_DETAIL,
            TPolicy.T_POLICY,
            TPolicyService.T_POLICY_SERVICE,
            TPolicyServiceApply.T_POLICY_SERVICE_APPLY,
            TPolicyServiceMaterial.T_POLICY_SERVICE_MATERIAL,
            TPolicyServiceRadix.T_POLICY_SERVICE_RADIX,
            TPolicyServiceSync.T_POLICY_SERVICE_SYNC,
            TProfessionAgent.T_PROFESSION_AGENT,
            TPropertyRightsTrading.T_PROPERTY_RIGHTS_TRADING,
            TQrCodeInfo.T_QR_CODE_INFO,
            TQuestionnaire.T_QUESTIONNAIRE,
            TRecommendation.T_RECOMMENDATION,
            TRisksShare.T_RISKS_SHARE,
            TRisksShareTrace.T_RISKS_SHARE_TRACE,
            TRiskshareApply.T_RISKSHARE_APPLY,
            TRiskshareApplyProcess.T_RISKSHARE_APPLY_PROCESS,
            TRiskshareDone.T_RISKSHARE_DONE,
            TRole.T_ROLE,
            TScoreTrace.T_SCORE_TRACE,
            TShopWare.T_SHOP_WARE,
            TShopWareInfo.T_SHOP_WARE_INFO,
            TSignRecord.T_SIGN_RECORD,
            TSiteMessage.T_SITE_MESSAGE,
            TSmallLoanOrder.T_SMALL_LOAN_ORDER,
            TSmallLoanProduct.T_SMALL_LOAN_PRODUCT,
            TSmallLoanTrace.T_SMALL_LOAN_TRACE,
            TSms.T_SMS,
            TStandardRate.T_STANDARD_RATE,
            TStaticSource.T_STATIC_SOURCE,
            TStaticSourceBak.T_STATIC_SOURCE_BAK,
            TStepBase.T_STEP_BASE,
            TStepButton.T_STEP_BUTTON,
            TTermBase.T_TERM_BASE,
            TThirdUser.T_THIRD_USER,
            TUser.T_USER,
            TUserCredit.T_USER_CREDIT,
            TUserCredittaskLog.T_USER_CREDITTASK_LOG,
            TUserInfoDetail.T_USER_INFO_DETAIL,
            TUserPropertyright.T_USER_PROPERTYRIGHT,
            TVillageCompanyBaseinfo.T_VILLAGE_COMPANY_BASEINFO,
            TVillageCompanyBusiness.T_VILLAGE_COMPANY_BUSINESS,
            TVillageCompanyCredit.T_VILLAGE_COMPANY_CREDIT,
            TVillageCompanyDetail.T_VILLAGE_COMPANY_DETAIL,
            TVillageCompanyEmployment.T_VILLAGE_COMPANY_EMPLOYMENT,
            TVillageCompanyEvaluation.T_VILLAGE_COMPANY_EVALUATION,
            TVillageCompanyFinance.T_VILLAGE_COMPANY_FINANCE,
            TVillageCompanyHonor.T_VILLAGE_COMPANY_HONOR,
            TVillageCompanyInsurance.T_VILLAGE_COMPANY_INSURANCE,
            TVillageCompanyInvestment.T_VILLAGE_COMPANY_INVESTMENT,
            TVillageCompanyKnowledge.T_VILLAGE_COMPANY_KNOWLEDGE,
            TVillageCompanyLoan.T_VILLAGE_COMPANY_LOAN,
            TVillageCompanyManagement.T_VILLAGE_COMPANY_MANAGEMENT,
            TVillageCompanyPatent.T_VILLAGE_COMPANY_PATENT,
            TVillageCompanyPayment.T_VILLAGE_COMPANY_PAYMENT,
            TVillageCompanyPurchase.T_VILLAGE_COMPANY_PURCHASE,
            TVillageCompanyReward.T_VILLAGE_COMPANY_REWARD,
            TVillageCompanySales.T_VILLAGE_COMPANY_SALES,
            TVillageCompanySubsidy.T_VILLAGE_COMPANY_SUBSIDY,
            TVillageCompanyWarrant.T_VILLAGE_COMPANY_WARRANT,
            TVillagePersonalAwardsPunishments.T_VILLAGE_PERSONAL_AWARDS_PUNISHMENTS,
            TVillagePersonalBaseinfo.T_VILLAGE_PERSONAL_BASEINFO,
            TVillagePersonalCarinfo.T_VILLAGE_PERSONAL_CARINFO,
            TVillagePersonalCreditRating.T_VILLAGE_PERSONAL_CREDIT_RATING,
            TVillagePersonalCreditTitle.T_VILLAGE_PERSONAL_CREDIT_TITLE,
            TVillagePersonalDetail.T_VILLAGE_PERSONAL_DETAIL,
            TVillagePersonalEquipment.T_VILLAGE_PERSONAL_EQUIPMENT,
            TVillagePersonalHouse.T_VILLAGE_PERSONAL_HOUSE,
            TVillagePersonalInsured.T_VILLAGE_PERSONAL_INSURED,
            TVillagePersonalOtherinfo.T_VILLAGE_PERSONAL_OTHERINFO,
            TVillagePersonalPatent.T_VILLAGE_PERSONAL_PATENT,
            TVillagePersonalPayment.T_VILLAGE_PERSONAL_PAYMENT,
            TVillagePersonalProductioninfo.T_VILLAGE_PERSONAL_PRODUCTIONINFO,
            TVillagePersonalPurchasing.T_VILLAGE_PERSONAL_PURCHASING,
            TVillagePersonalRecruitment.T_VILLAGE_PERSONAL_RECRUITMENT,
            TVillagePersonalWarrantinfo.T_VILLAGE_PERSONAL_WARRANTINFO,
            VStatisticsUser.V_STATISTICS_USER);
    }
}
